### ISSUE TITLE
Error while adding a template

### ISSUE THREAD

**Issue by lafpi** [micazi/flutter_templify#1]
Hi,

Since I upgraded to version 0.2.0 , running:
flutter_templify templates add -f ./template.yaml -ow
always return: 
Error in validating the Yaml configuration file supplied. Type Mismatch: structure must be a Map, but got YamlList. It may be due to the version variable. 

Do you have any clue on what I am doing wrong?

Regards, Pierre

name: "clean-code-template"
description: "A basic template for Clean Code Flutter apps"
isPackage: false
version: "0.0.0"
platforms:
  - ios
  - android
  - web
structure:
  - pubspec.yaml: "boilerplates/pubspec.yaml"

**Comment by lafpi** [comment]
The minimalist template that I use looks like this:

```
name: "clean-code-template"
description: "A basic template for Clean Code Flutter apps"
isPackage: false
version: "0.0.0"
platforms:
  - ios
  - android
  - web
structure:
  - pubspec.yaml: "boilerplates/pubspec.yaml"
```

**Comment by micazi** [comment]
Hey Pierre,
Thank you so much for your feedback.

Make sure that the structure you have is structured as a Map not a List.

So instead of doing this:
```yaml
structure:
  - file.dart
  - file2.dart : "./file-ref.dart"
```

You would do this:
```yaml
structure:
  file.dart
  file2.dart : "./file-ref.dart"
```

That would make it valid.

Regards,
Michael W. Aziz aka Micazi
